//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ExpenseItem
    {
        public int Id { get; set; }
        public int ExpenseId { get; set; }

        [Range(0, 100000, ErrorMessage = "Enter a valid amount")]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Invalid price: must be 2 digits after decimal")]
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }

        [Required]
        public string Description { get; set; }
    
        public virtual Expense Expense { get; set; }
    }
}
